addon/classes/Column.js
=> Add some clarification to docs

addon/classes/Table.js, tests/unit/classes/table-test.js
=> Add options hash to row creation methods

package.json, tests/dummy/app/templates/grouped.hbs, tests/dummy/app/templates/index.hbs
=> Fix dependencies

addon/components/light-table.js, addon/templates/components/light-table.hbs, addon/templates/components/lt-body.hbs, addon/templates/components/lt-foot.hbs, addon/templates/components/lt-head.hbs
=> [FEATURE] Style Table Element

addon/components/lt-infinity.js, addon/templates/components/lt-body.hbs
=> [BUGFIX] onScrolledToBottom doesnt get re-triggered when there arent enough rows in the table

addon/components/lt-infinity.js
@taras one of my coworkers uses this table for a local storage based app and noticed that the current version in master increased the load time 10x. This was because all records were prefetched and even though we schedule onScrolledToBottom on afterRender the page was frozen until all rows were rendered. Adding a small debounce solved the issue.
=> [BUGFIX] Debounce didEnterViewport

addon/-private/sync-array-proxy.js, tests/unit/classes/table-test.js
=> [BUGFIX] enableSync sorting duplicates records

addon/classes/Row.js
API doesn't make it clear how to get the data, so I think this should help.
=> Document `Row#content`

addon/components/lt-column-resizer.js, addon/templates/components/columns/base.hbs, tests/dummy/app/components/grouped-table.js, tests/dummy/app/components/resizable-table.js, tests/dummy/app/styles/table.less, tests/dummy/app/templates/components/resizable-table.hbs, tests/dummy/mirage/config.js
- Fix resizing in grouped columns
- Fix resizing in footer
- Performance improvements for `resizeOnDrag` 
@taras let me know what you think of this.
=> [BUGFIX] Resizable column improvements

package.json
=> Require ember-scrollable@^0.3.5

tests/dummy/mirage/config.js
=> [BUGFIX] Fix mirage config

package.json
This fix will resolve https://github.com/offirgolan/ember-light-table/issues/192
=> Fix for ember-composable-helpers addon incompatibility

package.json
=> Update ember-scrollable version

addon/components/lt-body.js, addon/components/lt-row.js, addon/templates/components/lt-body.hbs
Related to https://github.com/html-next/vertical-collection/issues/95
=> Removing setting of a row's elementId

addon/components/lt-body.js
follow up to https://github.com/offirgolan/ember-light-table/pull/426
=> Using HTMLElement.querySelector not document.querySelector

README.md
> - ![Slack Icon](https://i.imgur.com/Bjckhpc.png) **Slack**: We're happy to help you in our [**#e-light-table**][slack] Slack channel! You can [create an Ember Community Slack account][slackin] here for free.
[slack]: https://embercommunity.slack.com/messages/C615THVGF
[slackin]: https://ember-community-slackin.herokuapp.com/
=> readme: add link to #e-light-table Slack channel

.travis.yml, testem.js
=> ci/travis: use headless Chrome

.travis.yml, testem.js
https://github.com/ember-cli/ember-cli/pull/7148/files
=> ci: align Chrome headless usage with ember-cli 2.15

package.json, yarn.lock
see https://github.com/jmurphyau/ember-truth-helpers/releases/tag/v2.0.0
=> update ember-truth-helpers to latest version.

addon/templates/components/lt-body.hbs
=> fix(occlusion): remove colspan from loader and no-data spanned rows

config/ember-try.js
This should yield faster builds.
https://github.com/ember-cli/ember-try#yarn
=> chore(ci/ember-try): add useYarn

package.json, tests/integration/components/light-table-test.js, tests/integration/components/light-table/cells/base-test.js, tests/integration/components/light-table/columns/base-test.js, tests/integration/components/lt-body-test.js, tests/integration/components/lt-column-resizer-test.js, tests/integration/components/lt-foot-test.js, tests/integration/components/lt-infinity-test.js, tests/integration/components/lt-row-test.js, tests/integration/components/lt-scrollable-test.js, tests/integration/components/lt-spanned-row-test.js, yarn.lock
=> update test helpers

tests/dummy/app/router.js, tests/dummy/app/routes/cookbook/index.js, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/components/cookbook/index-list.hbs, tests/dummy/app/templates/cookbook/index.hbs, tests/dummy/app/templates/cookbook/occlusion-rendering.hbs
=> Adds cookbook/index

addon/components/lt-body.js, addon/components/lt-infinity.js, addon/styles/addon.css, addon/templates/components/lt-body.hbs, package.json, tests/integration/components/light-table-test.js, tests/integration/components/lt-infinity-test.js, yarn.lock
Trying to get IntersecitonObserver working.
- One option is to make the loader the height of the loading icon.  This would avoid jumps b/w reaching `lt-infinity` and showing the loading spinner
- noticing that bottom/top tolerance for IntersectionObserver is not being respected.
close #555
=> Update in viewport to use IntersectionObserver

package.json, yarn.lock
=> Upgrade ember-scrollable

addon/templates/components/columns/base.hbs
=> Avoid breaking line with sort icon in narrow columns

addon/mixins/draggable-column.js
Addresses https://github.com/offirgolan/ember-light-table/issues/595
=> [Draggable Column] Error when dragging column; "removeObject is not a function"

package.json, yarn.lock
https://github.com/salesforce/tough-cookie/issues/140
=> Pinning ip-regex to fix build issue.

package.json
=> bump vertical-collection to v1.0.0-beta.13

addon/mixins/table-header.js
=> refactor: Remove sendAction() calls

addon/mixins/draggable-column.js, package.json
Replace propertyWillChange/propertyDidChange with notifyPropertyChange and add polyfill for < Ember 3.1
=> Replace propertyWillChange/propertyDidChange with notifyPropertyChange

addon/helpers/compute.js
Removes leftover debugging line (this line was causing exceptions in my app)
=> Remove debugging line in compute helper

config/ember-try.js, package.json
=> Drop support to Ember 3.4 and 3.5

README.md, package.json
=> Update docs links

.github/workflows/ci.yml, .travis.yml, README.md, package.json
Min versions is v12.  CI setup for Node 14
=> Drop node 10

tests/integration/components/light-table-occlusion-test.js, tests/integration/components/light-table-test.js, tests/integration/components/light-table/cells/base-test.js, tests/integration/components/light-table/columns/base-test.js, tests/integration/components/lt-body-occlusion-test.js, tests/integration/components/lt-body-test.js, tests/integration/components/lt-column-resizer-test.js, tests/integration/components/lt-foot-test.js, tests/integration/components/lt-head-test.js, tests/integration/components/lt-infinity-test.js, tests/integration/components/lt-row-test.js, tests/integration/components/lt-scaffolding-row-test.js, tests/integration/components/lt-scrollable-test.js, tests/integration/components/lt-spanned-row-test.js, tests/integration/helpers/compute-test.js
=> qunit-dom codemod
