adopted-ember-addons/ember-light-table

addon/components/lt-cell.js

Right now when you leave out `{{t.head}}`, the table does not keep it's width per column, since they are only defined on the `thead`. With those changes it will always have the correct width.

[Bug Fix] Apply width on cell component based on it's columns width

---

addon/styles/addon.css
addon/templates/components/lt-body.hbs
package.json
tests/integration/components/light-table-test.js

Using a version of ember-scroll that's rewritten without dependency on trackpad-scroll-emulator jQuery Plugin.

Using native Ember trackpad scroll emulator

---

package.json
tests/dummy/app/styles/app.less
tests/dummy/app/templates/full.hbs
tests/integration/components/light-table-test.js

- Switched to release version of ember-scrollable
- Removed table container
- Made full-container a full container to force table height

Fixed full height demo

---

addon/components/light-table.js
addon/components/lt-body.js
addon/components/lt-foot.js
addon/components/lt-head.js
addon/mixins/table-header.js
addon/styles/addon.css
addon/templates/components/light-table.hbs
addon/templates/components/lt-body.hbs
addon/templates/components/lt-scrollable.hbs
tests/dummy/app/templates/expandable.hbs
tests/dummy/app/templates/grouped.hbs
tests/dummy/app/templates/index.hbs
tests/dummy/app/templates/selectable.hbs
tests/integration/components/light-table-test.js

Instead of having to explicitly set `virtualScrollbar: true`, we should just do it automatically if a fixed header or footer is defined. To do this while still keeping `fixed: true` on the `{{t.head}}` and `{{t.foot}}` contextual components, I have to pass some shared object around and do some logic via `run.scheduleOnce` in lt-body.js.

Determine virtualScrollbar via fixed header or footer

---

addon/classes/Table.js
tests/dummy/app/controllers/selectable.js
tests/dummy/app/controllers/table.js
tests/dummy/snippets/expandable-table.js
tests/dummy/snippets/grouped-table.js
tests/dummy/snippets/selectable-table.js
tests/dummy/snippets/simple-table.js

In many places, we're currently accessing with this.varName, which prevents people using computed properties.
Also, in my experience, this can be a confusing anti-pattern for those new to Ember. Many will copy from the demo app, so want to make sure people get used to this pattern.

Always use Ember object `get`.

---

addon/styles/addon.css

I find myself accidentally highlighting the table headers when clicking to sort:

Make text unselectable if column is sortable

---

addon/components/lt-infinity.js
package.json
tests/dummy/app/controllers/table.js
tests/dummy/app/routes/table-route.js

This is related to #108. When you sort and clear all the table rows from the table onScrolledToBottom gets triggered only once since the observer to get more data until out of viewport has been destroyed.

[BUGFIX] onScrolledToBottom doesnt get re-triggered after removing table rows

---

addon/components/cells/base.js
addon/components/columns/base.js
addon/components/light-table.js
addon/components/lt-column-resizer.js
addon/styles/addon.css
addon/templates/components/cells/base.hbs
addon/templates/components/lt-body.hbs
addon/templates/components/lt-row.hbs
addon/utils/css-styleify.js
ember-cli-build.js
package.json
tests/integration/components/light-table/cells/base-test.js
tests/integration/components/light-table/columns/base-test.js

Proposed Changes:
- Autoprefix addon.css (until PostCSS is up and running) + install ember-cli-autoprefixer to prefix demo page CSS
- Pass table instance + rawValue to custom cell component
- Use style instead of soon deprecated width attribute
- Remove readOnly from value so it can be modified
- Column resizer now applies width to table rows on mouseUp instead of on mouseMove
- I noticed a good amount of performance hits when the column width would be modified on mouseMove

Lots of fixes (about damn time!)

---

addon/classes/Table.js
tests/unit/classes/table-test.js

`flattenedColumns` was meant to be used only as private API but after working more and more with the table, I realized that having access to the list of all flattened columns is pretty useful (especially when building a column toggle sort of component).
I have decided to rename this property to `allColumns` which will now be part of the public API.

[FEATURE] Rename flattenedColumns to allColumns

---

addon/components/lt-column-resizer.js
addon/mixins/table-header.js
addon/templates/components/columns/base.hbs
addon/templates/components/lt-foot.hbs
addon/templates/components/lt-head.hbs

Fixes regression introduced in 1.2.0. 
Resize all cells in the column instead of just the header / footer

[FEATURE] Introduce `resizeOnDrag` for column resizing

---

addon/templates/components/lt-foot.hbs
addon/templates/components/lt-head.hbs
package.json

[BUGFIX] Add footer scaffolding and move width into style attr

---

addon/components/lt-body.js

no issue
- the three different types of row components were all named the same in the documentation

[DOCS] fix confusing property names for lt-body

---

addon/components/lt-head.js
blueprints/column-type/index.js

closes https://github.com/offirgolan/ember-light-table/issues/198

Docfix: lt-head and column-type blueprint

---

package.json

0.3.3 upgrade makes the tests run faster by removing autohide delay from `ember-scrollable`

Upgraded ember-scrollable to 0.3.3

---

addon/components/columns/base.js
addon/templates/components/columns/base.hbs

This puts `label` on the base column so it can be easily overwritten when defining new column types.

[FEATURE] Add label to base column to be used in column types

---

addon/classes/Row.js
addon/components/lt-body.js
addon/components/lt-row.js
addon/templates/components/lt-body.hbs
addon/templates/components/lt-scrollable.hbs
package.json
tests/dummy/app/components/scroll-controller.js
tests/dummy/app/controllers/scrolling.js
tests/dummy/app/router.js
tests/dummy/app/routes/scrolling.js
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/components/scroll-controller.hbs
tests/dummy/app/templates/scrolling.hbs
tests/dummy/snippets/scrolling.js

[FEATURE] ScrollTo and ScrollToRow

---

addon/classes/Column.js
addon/classes/Table.js
addon/components/light-table.js
blueprints/ember-light-table/index.js
package.json
tests/.jshintrc
tests/dummy/app/breakpoints.js
tests/dummy/app/controllers/responsive.js
tests/dummy/app/router.js
tests/dummy/app/routes/responsive.js
tests/dummy/app/styles/app.less
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/components/responsive-expanded-row.hbs
tests/dummy/app/templates/components/row-toggle.hbs
tests/dummy/app/templates/responsive.hbs
tests/dummy/snippets/responsive-table.js
tests/helpers/responsive.js

Resolves #219. 
This PR introduces a responsive solution. Using [ember-responsive](https://github.com/freshbooks/ember-responsive), I have introduced two methods to handle responsive behaviors that will hide the appropriate columns. This PR also introduces a new table property `responsiveHiddenColumns` to be able to easily distinguish between hidden columns and columns hidden from this responsive behavior.
Specify an array of media breakpoints that determine when this column will be shown. If we have the following breakpoints defined in `app/breakpoints.js`:
- mobile
- tablet
- desktop
And we want to show this column only for tablet and desktop media, the following array should be specified:
```js
{
breakpoints: ['tablet', 'desktop']
}
```
If this property is `null`, `undefined`, or `[]`, …

[FEATURE] Responsive Columns

---

addon/components/lt-body.js

Currently repeatedly setting the `scrollToRow` property to the same row doesn't work, because the `targetScrollOffset` isn't properly resetted.
This PR fixes that and also removes the unnecessary checks from #241.

[BUGFIX] repeated scrollToRow

---

addon/classes/Column.js
addon/classes/Row.js
addon/classes/Table.js
addon/components/cells/base.js
addon/components/columns/base.js
addon/components/lt-column-resizer.js
addon/mixins/draggable-column.js
addon/mixins/table-header.js
addon/styles/addon.css
addon/templates/components/columns/base.hbs
addon/templates/components/lt-foot.hbs
addon/templates/components/lt-head.hbs
tests/dummy/app/components/draggable-table.js
tests/dummy/app/mixins/table-common.js
tests/dummy/app/router.js
tests/dummy/app/routes/draggable.js
tests/dummy/app/styles/table.less
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/components/draggable-table.hbs
tests/dummy/app/templates/draggable.hbs
tests/unit/classes/column-test.js

Resolves #46.
Allows reordering of columns via drag n drop.
```js
/**
* Whether the column can be reorder via drag and drop.
*
* CSS Classes:
*  - `is-draggable`
*  - `is-dragging`
*  - `is-drag-target`
*    - `drag-left`
*    - `drag-right`
*
* @property draggable
* @type {Boolean}
* @default false
*/
draggable: false
/**
* Whether the column is a valid drop target.
*
* @property droppable
* @type {Boolean}
* @default true
*/
droppable: true
```
```js
/**
* onColumnDrag action.
*
* @event onColumnDrag
* @param  {Column} column The column that is being dragged
*/
onColumnDrag(column) {}
/**
* onColumnDrop action.
*
* @event onColumnDrop
* @param  {Column} column The column that was dropped
* @param  {Boolean} isSuccess The column was successfully dropped and sorted
*/
onColumnDrop(column, …
```

[FEATURE] Draggable Columns

---

addon/mixins/draggable-column.js

Resolves #273.
@lonelyghost any chance of you testing out this branch for me? I was able to get it working on a BrowserStack trial account in IE11 with this fix but I'm not able to check older versions.  
Fix found @ [Stack Overflow](http://stackoverflow.com/questions/26213011/html5-dragdrop-issue-in-internet-explorer-datatransfer-property-access-not-pos)

[BUGFIX] Resolve IE drag and drop crashes

---

addon/components/lt-body.js
tests/dummy/app/templates/components/selectable-table.hbs

Resolves #289. 
Select a row on click. If this is set to `false` and multiSelect is enabled, using click + `shift`, `cmd`, or `ctrl` will still work as intended, while clicking on the row will not set the row as selected.
/cc @karellm. Can you please check out this branch and test it out in your app?

[FEATURE] Add selectOnClick option

---

addon/templates/components/columns/base.hbs

Updated the `<span>` tag to an `<i>` tag in order to allow Semantic UI icons to appear. Font Awesome icons work in either and `<i>` tag or a <span> tag but Semantic UI icons only show up if they are wrapped in an `<i>` tag.

Change <span> to <i> tag for sorting icons

---

package.json

The `{{html-safe}}` helper [here](https://github.com/offirgolan/ember-light-table/blob/master/addon/templates/components/lt-foot.hbs#L7
) is the cause for the PR. The string helpers in `ember-composable-helpers` [were moved](https://github.com/DockYard/ember-composable-helpers/pull/237) to `ember-cli-string-helpers`, which is why that add-on is a `devDependency` of `ember-light-table`.
I have an Ember add-on which houses a paginated table component built using ELT. `ember-light-table` is listed as a dependency of that add-on. Installing that add-on in my engines and consuming app results in the following error: `Compile Error: html-safe is not a helper`. 
My fork has fixed this issue for me 🙃

Move ember-cli-string-helpers to dependencies

---

package.json

I removed `ember-truth-helpers` from devDependencies and updated to `1.3.0`.

Move ember-truth-helpers to dependencies

---

addon/templates/components/lt-body.hbs
addon/templates/components/lt-scrollable.hbs
tests/integration/components/light-table-test.js

After fixing deprecation message for onScroll, a typo was introduced by using `onScrollToY` instead of `onScrollY`. This PR resolves this problem by using the correct event handler and adds a basic test to ensure the event gets fired properly.

Fix broken onScroll handler after v1.8.6

---

tests/unit/classes/table-test.js

Adressing #419.
These tests assert that the computed property `table.isEmpty` is correct for tables that have `enableSync` set to `false` or `true`.

tests/table: isEmpty & isEmpty (enableSync = true)

---

README.md

I've been creating some new labels and cataloging all issues, so that it's easier for potential contributors to get started.
I also made it clear, that we're *reeeeally* interested in new feature ideas and possible use cases for ELT.
[Rendered](https://github.com/buschtoens/ember-light-table/blob/009cb1b06818af188f9e652afc48d2d7c8d0c8a6/README.md)

readme: add more information on collaborating

---

addon/classes/Column.js
addon/classes/Row.js
addon/classes/Table.js
addon/utils/fix-proto.js
tests/unit/classes/column-test.js
tests/unit/classes/row-test.js
tests/unit/classes/table-test.js
tests/unit/utils/fix-proto-test.js

Fixes #436.
This gives full support for stuff like this in IE <= 10:
```js
Table.reopen({
getFirstColumn() {
return this.get('columns.firstObject');
}
});
```
---
[MDN on `Object.prototype.__proto__`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/proto)
> ### [Internet Explorer](https://babeljs.io/docs/usage/caveats/#internet-explorer-classes-10-and-below-)
> #### Classes (10 and below)
> If you’re inheriting from a class then static properties are inherited from it via `__proto__`, this is widely supported but you may run into problems with much older browsers.
>
> **NOTE:** `__proto__` is not supported on IE <= 10 so static properties will not be inherited. See the [protoToAssign](https://babeljs.io/docs/plugins/transform-proto-to-assign/) for a …

Polyfill support for __proto__ in IE <= 10

---

addon/components/cells/base.js
addon/components/lt-body.js
addon/templates/components/lt-body.hbs
tests/integration/components/lt-body-test.js

This PR adds a scaffolding row (just like with `{{lt-head}}`) to the `{{lt-body}}` component.
This way it is possible to have a first row with colspans.
The scaffolding row can optionally be enabled like so:
```hbs
{{t.body enableScaffolding=true}}
```
Also removes the now unnecessary style attribute binding from `cells/base`, which in theory should yield a small performance boost. :rocket:

lt-body: add enableScaffolding option

---

package.json
tests/helpers/create-click-event.js
tests/helpers/has-class.js
tests/integration/components/light-table-test.js
tests/integration/components/light-table/cells/base-test.js
tests/integration/components/light-table/columns/base-test.js
tests/integration/components/lt-body-test.js
tests/integration/components/lt-column-resizer-test.js
tests/integration/components/lt-foot-test.js
tests/integration/components/lt-head-test.js
tests/integration/components/lt-infinity-test.js
tests/integration/components/lt-row-test.js
tests/integration/components/lt-scrollable-test.js
tests/integration/components/lt-spanned-row-test.js
yarn.lock

As promised. Moving to use `ember-native-dom-helpers` instead of jQuery selectors.
We should investigate using them in the addon code to make it jQuery-less

[chore]: Testing cleanup -- ember-native-dom-helpers

---

addon/components/lt-foot.js
addon/components/lt-head.js
addon/mixins/table-header.js

head & foot: make `table.height` optional, warn in `table-header` mixin

---

addon/classes/Table.js
tests/unit/classes/table-test.js

Fixes #414.
The tests assert that:
- the table is initialized with a synced array
- the synced array may be replaced
- the replacement array is correctly synced
- mutating the replaced array has no effect

Table: add `setRowsSynced` method

---

addon/components/columns/base.js
addon/mixins/table-header.js
addon/templates/components/columns/base.hbs
tests/dummy/app/templates/components/columns/draggable-table.hbs
tests/dummy/app/templates/components/columns/grouped-table.hbs
tests/dummy/app/templates/components/columns/resizable-table.hbs
tests/dummy/app/templates/components/cookbook/client-side-table.hbs
tests/dummy/app/templates/components/cookbook/custom-row-table.hbs
tests/dummy/app/templates/components/cookbook/horizontal-scrolling-table.hbs
tests/dummy/app/templates/components/cookbook/paginated-table.hbs
tests/dummy/app/templates/components/cookbook/table-actions-table.hbs
tests/dummy/app/templates/components/responsive-table.hbs
tests/dummy/app/templates/components/rows/expandable-table.hbs
tests/dummy/app/templates/components/rows/selectable-table.hbs
tests/dummy/app/templates/components/scrolling-table.hbs
tests/dummy/app/templates/components/simple-table.hbs
tests/integration/components/lt-head-test.js

light-table: add `iconSortable` property

---

addon/components/cells/base.js
addon/components/columns/base.js
addon/components/light-table.js
addon/components/lt-body.js
addon/components/lt-row.js
addon/mixins/table-header.js
addon/templates/components/cells/base.hbs
addon/templates/components/columns/base.hbs
addon/templates/components/light-table.hbs
addon/templates/components/lt-body.hbs
addon/templates/components/lt-foot.hbs
addon/templates/components/lt-head.hbs
addon/templates/components/lt-row.hbs
tests/integration/components/light-table-test.js

light-table: add `extra` property

---

package.json
yarn.lock

Rather than locking in to a fixed version of this dependency, allow newer versions of it too.
The yarn.lock diff is what I got after altering package.json and running `yarn` to install deps.

Loosen ember-one-way-controls version req

---

addon/mixins/draggable-column.js

`droppable` attribute is not respected when  dropping source column over target column where the attribute is set to false.
Just added a check on this PR for `droppable` attribute on target column. 
Related Issue : #494

Fix-Add droppable attribute check on target column before dropping source column

---

addon/mixins/draggable-column.js

closes #417 
[Special classes](http://offirgolan.github.io/ember-light-table/docs/classes/Column.html#property_draggable) are added to the cells that are being dragged over, so that they can be styled appropriately. However, `dragLeave` is not just triggered when the drag exits the cell, but also when the drag enters a child element inside the cell.
If the table is implemented with draggable columns, and also with either child elements inside the table header cells, or resizable columns, the `is-drag-target` class will be removed from the cell even while it is being dragged over. Resizable columns add a extra div (with class `lt-column-resizer`) inside the table header cell. This means that with both draggable and resizable columns, the drag target styling will rarely be applied when …

Ensure the drop target remains properly identified for draggable columns

---

package.json
yarn.lock

This is a minor bump and contains fixes, dependency updated, and
documentation updates so it should be safe to move to.
This is motivated by a conflict in our app with `ember-cli-dependency-lint`.

Update ember-cli-string-helpers to the latest version

---

README.md
addon/components/light-table.js
addon/components/lt-body.js
addon/styles/addon.css
addon/templates/components/lt-body.hbs
package.json
tests/dummy/app/components/cookbook/occluded-table.js
tests/dummy/app/router.js
tests/dummy/app/routes/cookbook/occlusion-rendering.js
tests/dummy/app/styles/table.less
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/components/cookbook/occluded-table.hbs
tests/dummy/app/templates/cookbook/occlusion-rendering.hbs
yarn.lock

**WHY**
https://github.com/offirgolan/ember-light-table/issues/12 https://github.com/offirgolan/ember-light-table/issues/435
Especially https://github.com/offirgolan/ember-light-table/issues/12#issuecomment-318963414
**WHAT**
This PR introduces experimental integration with https://github.com/html-next/vertical-collection, as it is nearing a `1.0` in terms of stability. By setting the `occlusion=true` flag and setting a value for `estimatedRowHeight`, we deactivate `ember-scrollable` and use `vertical-collection` instead.
There is a new section in the cookbook `cookbook/occlusion-rendering` where an example is live
Some compromises with respect to functionality are made with this initial release so that it can get into people's hands and begin testing and playing with it. These are listed …

[FEATURE occlusion]: Preliminary Vertical collection integration 

---

package.json
yarn.lock

This version bump of ember-scrollable just contains dependency updates.

Update ember-scrollable to the latest version

---

addon/components/light-table.js
addon/components/lt-body.js
addon/mixins/table-header.js
addon/styles/addon.css
addon/templates/components/lt-body.hbs
ember-cli-build.js
tests/dummy/app/components/cookbook/occluded-table.js
tests/dummy/app/templates/components/cookbook/occluded-table.hbs

Fixes #486 by using Flexbox instead of `getBoundingClientRect`. :tada: 
Fixes #484 by using the intrinsic sizing.
Also makes sure that the padding applied (to account for the scrollbar) is in fact the size of the browser scrollbar, which may vary from browser to browser and OS to OS, so this kinda solves #487.

fix(occlusion): sizing

---

addon/components/lt-body.js
addon/templates/components/lt-body.hbs
tests/dummy/app/templates/components/cookbook/occluded-table.hbs
tests/dummy/mirage/scenarios/default.js

fix(occlusion): pass bufferSize based on scrollBuffer

---

addon/mixins/draggable-column.js

When dragging a non-column component over a column the mixin `draggable-column.js` checks to see if it is a drop target. This is fine when you are dragging a column but when a dragging something like a row `isDropTarget` fails as `sourceColumn` is undefined `sourceColumn.get('parent')`
This fix checks to see if `sourceColumn` is defined before trying to access `sourceColumn.get('parent')`

Guard against undefined sourceColumn

---

addon/classes/Table.js
tests/unit/classes/table-test.js

This fixes table construction for ember data types such as `DS.RecordArray` and `DS.AdapterPopulatedRecordArray`. Otherwise it does not work with ember data’s `store.findAll('user')` result since `instanceof` check returns false.

Use isArray to check columns, rows type

---

addon/components/cells/base.js

This is related to #12 .
The utils method `cssStyleify` is not scalable when displaying many cells.
Indeed, the method do the following on every cell
- Introspect each object to get the keys
- Instantiate a new array
- Iterate over the `hash` object
- Try to dasherize the key
- `HtmlSafe` the returned string
This leads to a lot of memory management operations (including garbage collection phases) for the JS VM and it's very slow.
We can get a significant performance gain by bypassing `cssSyleify` in this case.

Improve cells performance

---

addon/components/cells/base.js

Seeing large numbers of these warnings: `Binding style attributes may introduce cross-site scripting vulnerabilities ...` on Ember 3.3.2.
The empty string being returned when there is no `columnWidth` needed to be wrapped in `htmlSafe()` or changed to `null`. Also I think the `htmlSafe()` call needs to wrap the entire `width: ...` style.

FIX - Incomplete use of htmlSafe() on Cell.style

---

addon/components/light-table.js
addon/components/lt-body.js
addon/components/lt-column-resizer.js
addon/mixins/draggable-column.js
yarn.lock

This fixes #587.
CC: @buschtoens

replace `sendAction` with modern callable methods

---

addon/components/lt-column-resizer.js
addon/components/lt-infinity.js
addon/utils/closest.js
tests/helpers/table-columns.js
tests/integration/components/light-table-test.js

Fixes #591
CC: @alexander-alvarez I left usage of `this.$().text().trim` in the test blueprint. I'm going to make a seperate PR for updating ember + friends so we can get qunit dom working.
I'm also going to make a PR against ember-scrollable to remove that little bit of jQuery as well.

Remove jQuery usage

---

.travis.yml
config/ember-try.js
package.json
tests/integration/components/light-table-occlusion-test.js

1. Assert compatibility with Ember 3.x in package.json
2. Add LTS 3.4 to ember-try scenarios
3. Fix tests to pass in LTS 3.4

Assert and Test compatibility with LTS 3.4

---

addon/templates/components/lt-body.hbs
tests/integration/components/light-table-test.js

When multiple tables were rendered to the document, only the first table would scroll correctly. This was due to the  selector referencing a class name and ember-in-viewport only selecting the first instance of that class. This commit prepends a table ID to that selector so that multiple tables with scrolling is supported.

Fixing issue with multiple tables and onScrolledToBottom.

---

addon/-private/global-options.js
package.json

Fixes #667
Based on guide here https://deprecations.emberjs.com/v3.x/#toc_ember-polyfills-deprecate-merge
Given that this addon doesn't support <2.12 I've not bothered to include the assign polyfill, but let me know if you think we need to to anything further.

Replace merge with assign

---

addon/templates/components/lt-body.hbs
addon/templates/components/lt-scrollable.hbs

Fixes #676 
Essentially this ensures that ember-scrollable is 'resized' when rows are updated - based on the ember-scrollable guidance [here](https://github.com/alphasights/ember-scrollable/blob/master/addon/components/ember-scrollable.js#L448...L470 ) 
Which comes from [this](https://github.com/alphasights/ember-scrollable/issues/85) ember-scrollable issue.
I'm not entirely sure the best way to test this - any ideas @alexander-alvarez ?

ensure ember-scrollable updates when rows are updated

---

.travis.yml
README.md
config/ember-try.js
package.json

Based on the community [survey results](https://emberjs.com/ember-community-survey-2019/) there is still enough of a user base for 2.18 that we'll need to maintain support for a little longer while people continue to upgrade to ember 3.x. 
2.18 is a sensible place to stop as a number of polyfills for new behaviour only go back to 2.18 and continuing to support older versions will make it harder to keep up with the pace of ember development.
Don't merge until #696 (sorry I stupidly chained these branches together locally).

Set minimum supported ember version at 2.18

---

.travis.yml
README.md
config/ember-try.js
package.json

See #701 for more info - essentially the change in the API back to conventional EmberObject initialization has issues with ember 2.18. Whilst I'm sure these could be resolved it's holding up releasing #701 which is essential for newer versions (ember 3.11+) of Ember. 
If there is a strong backlash to this change on 2-x branch then we can look to restoring support - otherwise those using ember <3.4 should stick with the master branch.

BREAKING drop support for ember 2.18

---

addon/classes/Column.js
addon/classes/Row.js
addon/classes/Table.js
addon/index.js
blueprints/cell-type-test/files/tests/integration/components/light-table/cells/__name__-test.js
blueprints/column-type-test/files/tests/integration/components/light-table/columns/__name__-test.js
tests/dummy/app/mixins/table-common.js
tests/integration/components/light-table-occlusion-test.js
tests/integration/components/light-table-test.js
tests/integration/components/light-table/cells/base-test.js
tests/integration/components/light-table/columns/base-test.js
tests/integration/components/lt-body-occlusion-test.js
tests/integration/components/lt-body-test.js
tests/integration/components/lt-head-test.js
tests/unit/classes/column-test.js
tests/unit/classes/row-test.js
tests/unit/classes/table-test.js
tests/unit/utils/fix-proto-test.js

This is a breaking change as it converts the new Class() syntax to Class.create().
In addition, the only way I could get these to work was to convert the positional arguments to named args in an options hashes:
`new Table(columns, rows)` => `Table.create(columns: columns, rows: rows)`
`new Row(content, options)` => `Row.create({ content: content })`
`new Column(opts)` => `Column.create(opts)`
We’ve had to replace the native constructor methods with emberObject init methods as per the official docs which should also fix #699. As a result we’ve removed the Ember 2.12 ‘hacks’ which shouldn’t be an issue as we’ve bumped ember version minimum version to 2.18.
Clearly there are issues with ember 2.18 that need resolving but @alexander-alvarez what are your thoughts so far?

WIP [BREAKING] fixes #444 #662 converts ES6 native classes to ember objects

---

addon/components/lt-column-resizer.js
addon/mixins/draggable-column.js

This fixes Ember 3.9 deprecation for volatile computed properties.

Replace volatile computed properties

---

addon/components/lt-column-resizer.js
addon/components/lt-scaffolding-row.js
addon/templates/components/lt-foot.hbs
addon/templates/components/lt-head.hbs
addon/templates/components/lt-scaffolding-row.hbs
app/components/lt-scaffolding-row.js
tests/integration/components/lt-scaffolding-row-test.js

This fixes #719.
Additionally to fixing above issue, this fixes a bug I found, which occurs in following scenario: 
When table columns have no sub columns, header cells are not moving while footer cells are being resized. 
One thing to note, is minor refactoring that I did - extracting some repetitive code to `lt-scaffolding-row` component.

Fix resizing columns issues(2.x)

---

addon/components/columns/base.js

This maintains existing behaviour whilst removing the deprecation warning.

Fix deprecation warning for overridden rowspan computed property

---

package.json
tests/dummy/app/adapters/application.js
tests/dummy/app/components/base-table.js
tests/dummy/app/components/code-panel.js
tests/dummy/app/components/colored-row.js
tests/dummy/app/components/columns/draggable-table.js
tests/dummy/app/components/columns/grouped-table.js
tests/dummy/app/components/columns/resizable-table.js
tests/dummy/app/components/cookbook/client-side-table.js
tests/dummy/app/components/cookbook/custom-row-table.js
tests/dummy/app/components/cookbook/custom-sort-icon-table.js
tests/dummy/app/components/cookbook/horizontal-scrolling-table.js
tests/dummy/app/components/cookbook/occluded-table.js
tests/dummy/app/components/cookbook/paginated-table.js
tests/dummy/app/components/cookbook/table-actions-table.js
tests/dummy/app/components/materialize-icon.js
tests/dummy/app/components/responsive-table.js
tests/dummy/app/components/rows/expandable-table.js
tests/dummy/app/components/rows/selectable-table.js
tests/dummy/app/components/scrolling-table.js
tests/dummy/app/components/simple-table.js
tests/dummy/app/models/user.js
tests/dummy/app/routes/table-route.js
tests/dummy/app/templates/components/cookbook/client-side-table.hbs
tests/dummy/app/templates/components/materialize-icon.hbs
tests/dummy/app/templates/components/scrolling-table.hbs

Still requires ember @classic decorator until addon is converted.

Convert dummy app

---

addon/components/light-table.hbs
addon/components/light-table.js

Could be breaking, simply because of not being able to pass a different `tagName` in etc

Make light-table tagless

---

addon/components/light-table.hbs

Right now we are using this Addon in our build and getting the following deprecation
https://deprecations.emberjs.com/v3.x/#toc_attrs-arg-access
This should fix it

FIx deprecation for using this.attrs for arguments in template
